### ISSUE TITLE
Mime types do not work

### ISSUE THREAD

**Issue by tomswinkels** [vpapaloukas/laravel-url-uploaded-file#1]
```
$source = UrlUploadedFile::createFromUrl('https://sena-studiomessenger.s3.eu-central-1.amazonaws.com/userdata/7/audio/2022/6/8/20220608_111556_bc4367d1-b47b-461e-ad13-9203629616db_transcoded.mp3');
dump($source->getMimeType());
```

Result:

`application/octet-stream`

**Comment by vpapaloukas** [comment]
The url you provided getrs a file full of nulls in the beginning. 

I don't know if it is amazonaws that causes this or it is a problem with lame encoder used in the mp3.

Fetching an mp3 from another url it returns correct mime audio/mpeg.
